### ISSUE TITLE
SI: asan crash when teleporting in Sleeping Bull

### ISSUE THREAD

**Issue by mbanck** [exult/exult#40]
when I use the switches below Sleeping Bull to teleport in one of the chambers, and then hit the switch to teleport back, I got this crash:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==10380==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x559fd232c367 bp 0x000000000000 sp 0x7ffe39394940 T0)
==10380==The signal is caused by a READ memory access.
==10380==Hint: address points to the zero page.
    #0 0x559fd232c366 in Map_chunk::remove(Game_object*) objs/chunks.cc:840
    #1 0x559fd21c6711 in Usecode_internal::set_item_shape(Usecode_value&, Usecode_value&) usecode/ucinternal.cc:799
    #2 0x559fd222c2b2 in Usecode_internal::UI_set_item_shape(int, Usecode_value*) usecode/intrinsics.cc:215
    #3 0x559fd21c2d2f in Usecode_internal::Execute_Intrinsic(Usecode_value (Usecode_internal::*)(int, Usecode_value*), char const*, int, int, Usecode_value*) usecode/ucinternal.cc:1605
    #4 0x559fd21c2d2f in Usecode_internal::call_intrinsic(int, int) usecode/ucinternal.cc:1669
    #5 0x559fd21d6950 in Usecode_internal::run() usecode/ucinternal.cc:2598
    #6 0x559fd21e6d62 in Usecode_internal::call_usecode(int, Game_object*, Usecode_machine::Usecode_events) usecode/ucinternal.cc:2990
    #7 0x559fd235e1c2 in Game_object::activate(int) objs/objs.cc:1027
    #8 0x559fd235e1c2 in Game_object::activate(int) objs/objs.cc:1017
    #9 0x559fd1a267fa in Activate_actor_action::handle_event(Actor*) actions.cc:695
    #10 0x559fd1a27fdb in Actor_action::handle_event_safely(Actor*, bool&) actions.cc:61
    #11 0x559fd1a27fdb in Sequence_actor_action::handle_event(Actor*) actions.cc:807
    #12 0x559fd1a27fdb in Actor_action::handle_event_safely(Actor*, bool&) actions.cc:61
    #13 0x559fd1a27fdb in Sequence_actor_action::handle_event(Actor*) actions.cc:807
    #14 0x559fd1a2f358 in Path_walking_actor_action::handle_event(Actor*) actions.cc:208
    #15 0x559fd1a6ff26 in Npc_actor::handle_event(unsigned long, unsigned long) actors.cc:5020
    #16 0x559fd1c59d4c in Time_queue::activate0(unsigned int) tqueue.cc:198
    #17 0x559fd1b16161 in Time_queue::activate(unsigned int) tqueue.h:119
    #18 0x559fd1b16161 in Time_queue::activate(unsigned int) tqueue.h:114
    #19 0x559fd1b16161 in Handle_events exult.cc:1265
    #20 0x559fd1b16161 in Play exult.cc:1056
    #21 0x559fd1b16161 in exult_main exult.cc:713
    #22 0x559fd191bb53 in main exult.cc:409
    #23 0x7f54a85f609a in __libc_start_main ../csu/libc-start.c:308
    #24 0x559fd1922749  (/usr/games/exult+0xde749)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV objs/chunks.cc:840 in Map_chunk::remove(Game_object*)
==10380==ABORTING
```

Leaving this here for the time being and trying to reproduce, but it's been a while since I last saved.

**Comment by mbanck** [comment]
Not directly reproducible unfortunately.

**Comment by marzojr** [comment]
Just so I know where to look form is this on v1.6.x or master?

**Comment by mbanck** [comment]
I'm using v1.6.x

**Comment by DominusExult** [comment]
This has been so long and things changed a lot since then, so I'm closing it for now.
